nelmio_cors:
  defaults:
    allow_credentials: true
    allow_origin: ['http://localhost:3000','https://pomodoro-app-three-lyart.vercel.app']
    allow_headers: ['Authorization', 'Content-Type']
    allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
    max_age: 3600

  paths:
    '^/api/':
      allow_origin: ['http://localhost:3000','https://pomodoro-app-three-lyart.vercel.app']
      allow_headers: ['Authorization', 'Content-Type']
      allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
